### ISSUE TITLE
In-person meet up @ MoneroKon2023

### ISSUE THREAD

**Issue by ajs-xmr** [Shoalsteed/Community-Meeting#8]
Hello,

I am one of the organizers of [Monero Konferenco](https://monerokon.com). We had a few I2P community members at our last event and we would be more than happy to host an in-person meet up for the next one. We are currently in the [crowdfunding](https://ccs.getmonero.org/proposals/monerokon-2023-ccs-1.html) process and it is highly likely the event will be held on 23rd-25th June 2023 at [Parallel Polis](https://www.paralelnipolis.cz)/[La Fabrika](https://www.lafabrika.cz/en/lafabrika) in Prague, Czech Republic.

Besides the social aspect of a meet up, we would welcome technical talks on I2P and/or hands-on training sessions on how to set up I2P, how to become a reseed operator, how to integrate I2P into an app, etc. You can find CFP submission form [here](https://cfp.monerokon.com/2023/cfp).

ajs

**Comment by diva-exchange** [comment]
DIVA would like to present the latest development "I2P-based-bockchain and DEX framework, 100% selfhosted, 100% open-source" [please note: DIVA will only present testnet based things - never on a mainnet or alike].

An "official" placeholder invitation by monerokon for DIVA (travel costs and stuff covered by diva.exchange association - so no budget needed from monerokon) would still be really much appreciated. Reason: the CfP is a bit difficult for DIVA, since development & research of new stuff will take for sure until Mai 2023. Advantage for monerokon: it will be again new stuff from DIVA.

**Comment by ajs-xmr** [comment]
Hi @diva-exchange. All [CfP](https://cfp.monerokon.com/2023/cfp) submissions will go through a selection process and voted on between 3rd-17th April 2023 by a group of "Reviewers" (anyone can volunteer to be a Reviewer by commenting [here](https://github.com/MoneroKon/meta/issues/4)). Notice of Acceptance should be sent out by 18th April 2023.

With that said, the submission does not have to be really detailed. Just a very general description of what will be presented would do. We really enjoyed your talk in Lisbon (as well as the refreshing elderflower syrup) and would love to see you guys again in Prague.
